### ISSUE TITLE
fix: history command (fc -e)

### ISSUE THREAD

**Issue by Pro696969** [acmpesuecc/psh_hn6#4]
```fc -e <text editor name>```
 Should display the last executed command in the text editor opened.

**Comment by anirudh-os** [comment]
Can I have this issue assigned ?

**Comment by Pro696969** [comment]
!assign 45

**Comment by Pro696969** [comment]
!assign @anirudh-os 45

**Comment by anirudh-os** [comment]
I am going for dinner so can i get my time extended ?

**Comment by Pro696969** [comment]
ping us when you are back @anirudh-os

**Comment by anirudh-os** [comment]
@Pro696969 I just came back. Can I continue ?

**Comment by Pro696969** [comment]
!assign @anirudh-os 60

**Comment by Pro696969** [comment]
!deassign

**Comment by anirudh-os** [comment]
Uhh I am still working on this issue. Can i continue ? I just realised i that was deassigned @Pro696969

**Comment by Pro696969** [comment]
!assign @anirudh-os 60

**Comment by anirudh-os** [comment]
I am still working on this

**Comment by Pro696969** [comment]
how much time do u need, ill assign it

**Comment by anirudh-os** [comment]
I can't really say. I have found the bug and am still trying to fix it.

**Comment by Pro696969** [comment]
!assign @anirudh-os 60

**Comment by anirudh-os** [comment]
Please don't deassign me. I am still working on it.

**Comment by Pro696969** [comment]
!assign @anirudh-os 60

**Comment by Pro696969** [comment]
!deassign

**Comment by Pro696969** [comment]
!assign @anirudh-os 120

**Comment by anirudh-os** [comment]
@Pro696969 So the issue is to display the recently executed commands in a temporary file right ? I was finally able to do that. If there aren't any extra constraints, can i create a pr ?

**Comment by Pro696969** [comment]
ill look into it now

**Comment by anirudh-os** [comment]
@Pro696969 Ok

**Comment by AlaynaMonteiro** [comment]
!deassign

**Comment by VulcanRaven737** [comment]
Can I please be assigned to it?

**Comment by Pro696969** [comment]
Sorry this issue is solved
